# -*- coding: utf-8 -*-
"""txt_to_img.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0Jn8Lc7_wnbBsmCEwPYwicFfJ7WPGCK
"""

!pip install diffusers transformers accelerate torch torchvision
!pip install matplotlib

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

# Use a simpler, more compatible model
model_id = "runwayml/stable-diffusion-v1-5"

print("Loading Stable Diffusion v1-5...")

try:
    pipe = StableDiffusionPipeline.from_pretrained(model_id)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    pipe = pipe.to(device)
    print(f"Model loaded successfully on {device}!")
except Exception as e:
    print(f"Error: {e}")

def generate_simple(prompt):
    """Simple image generation function"""
    try:
        image = pipe(
            prompt,
            num_inference_steps=20,
            guidance_scale=7.5,
            width=512,
            height=512
        ).images[0]

        plt.figure(figsize=(8, 8))
        plt.imshow(image)
        plt.axis('off')
        plt.title(prompt)
        plt.show()
        return image

    except Exception as e:
        print(f"Generation error: {e}")
        return None

# Test the simple version
generate_simple("ninja")